### ISSUE TITLE
[backend] 42 oauth 

### ISSUE THREAD

**Issue by seohl16** [ft-nobrand/ft_transcendence#10]
- 42 oauth functions created

**Comment by seohl16** [comment]
## Docker-compose yaml 파일 
### docker-compose.yaml 
```
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./packages/backend
      target: development
    volumes:
      - ./packages/backend/:/usr/src/app
      - /src/app/node_modules
    env_file:
    - .env
    command: npm run start:dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
      - db-network
    restart: always

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./packages/frontend
      target: development
    volumes:
      - ./packages/frontend/:/usr/src/app
      - /src/app/node_modules
    ports:
      - "3030:3030"
    env_file:
    - .env
    command: npm run dev
    restart: always

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - db-network
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "5050:80"
    networks:
      - db-network
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    restart: always
    container_name: pgadmin

volumes:
  docker-nest-postgres:

networks:
  app-network:
  db-network:
```

### pgadmin 사용 방법 
![스크린샷 2022-08-02 오후 5 59 52](https://user-images.githubusercontent.com/68208055/182336107-a6564c84-ab31-4175-9739-bc7709b50c81.png)
1. http://localhost:5050 접속하고 register-server를 눌러 새로운 서버를 등록한다. 

![스크린샷 2022-08-02 오후 6 00 22](https://user-images.githubusercontent.com/68208055/182336083-ae1409b8-7c88-4f50-938e-332fc6e950ae.png)
2. server 이름을 정한다. 


![스크린샷 2022-08-02 오후 6 00 08](https://user-images.githubusercontent.com/68208055/182336102-43f45329-0b10-47fd-9d80-890ea60dd0ee.png)
3. connection tab에 가서 postgres (hostname) port (5432) maintaindatabase (docker-nest-postgres) databaseusername (postgres) databasepassword (postgres)

4. schema - table에 들어가서 필요한 테이블을 본다.
